# -*- coding: utf-8 -*-
"""MLTraining4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9LnsXpCN-TBhFZinX-w75wI4N6Vp2r7
"""

# DATA COLLECTION 
# DATA INTEGRATION
# DATA PREPROCESSING
# DATA CLEANING
# TRAINING   SK LEARN SCI KIT LEARN
# TESTING
# NUMPY PANDAS MATPLOTLIB, SEABORN, SCIKITLEARN

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df =  pd.read_csv("/content/student_info.csv")

df.head()   # Returns top 5 rows

df.tail()    # Returns bottom 5 rows

df.shape # Rows, Columns

df.info()

df.describe()

df.isnull().sum()

df.mean()

df2 = df.fillna(df.mean())

df2.isnull().sum()

from sklearn.model_selection import train_test_split

# X = Study hours  X = ["study_hours"]  NOT marks 
# y = Marks     output  y = ["Student_marks"]  NOT STUDY HOURS

X = df2.drop("student_marks", axis="columns") # INPUT
y = df2.drop("study_hours" ,  axis="columns") # OUTPUT

X_train, X_test , y_train, y_test = train_test_split(X,y, test_size = 0.2)

# LINEAR REGRESSION y = mx+c

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

# TRAINING  

lr.fit(X_train , y_train)  # Ctrl + f9 run all cells

# TESTING
y_pred = lr.predict(X_test)
y_pred

# THREE COLUMN 

# X_TEST , Y_TEST , Y_PRED


pd.DataFrame(np.c_[X_test, y_test , y_pred] , columns = ["Study Hours" , "Original Marks" , "Predicted Marks"])

lr.score(X_test, y_test)

# The model is working with 96% accuracy.